#!/bin/bash

export POSTGRES_PASSWORD=$(kubectl get secret --namespace default $STACKMAP_DB_HOST -o jsonpath="{.data.postgres-password}" | base64 -d)

export sqlcmd=$(cat create_table.sql)

project=$1

sqlcmd="CREATE SCHEMA project_$project; set schema 'project_$project'; set search_path = project_$project, public;  $sqlcmd"


kubectl run postgresql-client-project --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:15.0.0-debian-11-r3 --env="PGPASSWORD=$POSTGRES_PASSWORD"       --command -- psql --host $STACKMAP_DB_HOST -U postgres -d postgres -p 5432 -c "$sqlcmd"

