#!/bin/bash

#helm install --wait postgresql bitnami/postgresql
#helm install postgresql oci://registry-1.docker.io/bitnamicharts/postgresql-ha
helm install --wait stackmap-db oci://registry-1.docker.io/bitnamicharts/postgresql

export STACKMAP_DB_HOST=stackmap-db-postgresql

./enable_extension


./create_project vedur
