#!/bin/bash

#helm install --wait postgresql bitnami/postgresql
helm install postgresql oci://registry-1.docker.io/bitnamicharts/postgresql-ha

./enable_extension

#./create_table

./create_project vedur
