#!/bin/bash

export POSTGRES_PASSWORD=$(kubectl get secret --namespace default $STACKMAP_DB_HOST -o jsonpath="{.data.postgres-password}" | base64 -d)

kubectl run postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:15.0.0-debian-11-r3 --env="PGPASSWORD=$POSTGRES_PASSWORD"       --command -- psql --host $STACKMAP_DB_HOST -U postgres -d postgres -p 5432 -c "CREATE EXTENSION IF NOT EXISTS postgis; CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"


